version: '3'

services:
  adblock_dns:
    image: ragibkl/adblock_dns:default
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
    network_mode: host
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "20"
    volumes:
      - logs:/logs
    labels:
      - com.centurylinklabs.watchtower.enable=true

  adblock_http:
    image: ragibkl/adblock_http
    restart: always
    ports:
      - 80:80
      - 443:443
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "20"
    labels:
      - com.centurylinklabs.watchtower.enable=true

  logs_viewer:
    image: ragibkl/adblock_logs_viewer
    restart: always
    ports:
      - 8080:8080
    network_mode: host
    volumes:
      - logs:/logs
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    image: v2tec/watchtower
    command: --cleanup --label-enable --interval 3600
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  logs:
