version: '3'

services:
  adblock_dns:
    image: ragibkl/adblock_dns:default
    restart: always
    ports:
      - 1153:53/tcp
      - 1153:53/udp
    env_file: .env
    volumes:
      - logs:/logs
    labels:
      - com.centurylinklabs.watchtower.enable=true

  dnsdist:
    image: ragibkl/adblock_dnsdist
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - letsencrypt:/etc/letsencrypt
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    image: v2tec/watchtower
    command: --cleanup --label-enable
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  logs:
  letsencrypt:
