name: dnsdist Docker Image CI

on:
  push:
    branches: ["master"]
    paths:
      - adblock_dnsdist/**
      - .github/workflows/build-dnsdist-docker-image.yml
  pull_request:
    branches: ["master"]
    paths:
      - adblock_dnsdist/**
      - .github/workflows/build-dnsdist-docker-image.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Docker image
        run: ./scripts/build.sh
        working-directory: ./adblock_dnsdist
